### ISSUE TITLE
pytest mark behaviours incorrect

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#25]
**Describe the bug**

Applies to branch 15-gtfs-validation-pipeline.

**Environment**

 - OS: macos
 - Python version: 3.9.13

**Steps to reproduce**

Each mark runs only the standard test suite and those marked with the corresponding pattern. Eg pytest -runfoo would run the "foo" marked test & the main suite, but not anything marked with "bar".

**Comment by ethan-moss** [comment]
Was able to replicate this behaviour during the PR review of `15-gtfs-validation`. 

Essentially, this issue is caused when the _'if config.getoption() then return'_ part of the logic was duplicated when adding the `--runinteg` and `--runexpensive` flags. It works when there is only a single flag to consider, but adding in multiple flags means the logic does not work, since whenever any flag was added the return logic would kick in and it would run the whole test suite (only marking the preceding tests in the order they were defined in the function - runsetup, runinteg, and then runexpensive)  

So, this needs to be changed so that all the unit tests are run if and only if when all the flags are given. Then in the case when a subset of flags are provided, do not add a mark for skipping those respective tests (such that when a flag is given no marks are added and the tests run).

The following change seems to fix the issue:
```python
def pytest_collection_modifyitems(config, items):
    """Handle switching based on cli args."""
    if (
        config.getoption("--runsetup")
        & config.getoption("--runinteg")
        & config.getoption("--runexpensive")
    ):
        # do full test suite when all flags are given
        return

    # do not add marks when the runsetup flag is given
    if not config.getoption("--runsetup"):
        skip_setup = pytest.mark.skip(reason="need --runsetup option to run")
        for item in items:
            if "setup" in item.keywords:
                item.add_marker(skip_setup)

    # do not add marks when the runinteg flag is given
    if not config.getoption("--runinteg"):
        skip_runinteg = pytest.mark.skip(
            reason="need --runinteg option to run"
        )
        for item in items:
            if "runinteg" in item.keywords:
                item.add_marker(skip_runinteg)

    # do not add marks when the runexpensive flag is given
    if not config.getoption("--runexpensive"):
        skip_runexpensive = pytest.mark.skip(
            reason="need --runexpensive option to run"
        )
        for item in items:
            if "runexpensive" in item.keywords:
                item.add_marker(skip_runexpensive)
```

**Comment by ethan-moss** [comment]
Tested with the above snippet added, replacing the existing function:

> Note: only `--runsetup` and `--runinteg` flags are utilised by the pytest suite in the `25-pytest-mark-behaviours` branch.

| Flag config | Result |
| :--- |  :--- |
| No flags | All tests without a flag run, OK |
| Only `--runsetup` | All tests run except those that have the `runinteg` mark, OK |
| Only `--runinteg` | All tests run except those that have the `runsetup` mark, OK |
| Both `--runsetup --runinteg` | Entire test suite runs, OK |

Testing all possible flag configurations shows the pytest marks work as expected with this fix in place. Will raise a PR to merge in the change.
