### ISSUE TITLE
`_check_parent_dir_exists()` does not create a directory when `create=True`

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#61]
**Describe the bug**

Running [`_check_parent_dir_exists()`](https://github.com/datasciencecampus/transport-network-performance/blob/96f48a9588b8e119812fad18e21cb8481b325bc5/src/transport_performance/utils/defence.py#L31) does not create a directory when `create=True` AND the requested path is a new parent folder with a child subfolder. This is because `os.mkdir()` does not create new folders recursively. Here is an example: 

```bash
>>> import os
>>> os.mkdir("outputs/gtfs") # works OK, so delete folder and try with grandchild
>>> os.mkdir("outputs/gtfs/validation")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/gtfs/validation'
```
[StackOverflow](https://stackoverflow.com/questions/6004073/how-can-i-create-directories-recursively) suggests using [`os.makedirs()`](https://docs.python.org/3/library/os.html#os.makedirs) :
```bash
>>> os.makedirs("outputs/gtfs/validation") # grandchild created as expected.
```
This could be dropped in directly to replace `os.mkdir` [link to code line](https://github.com/datasciencecampus/transport-network-performance/blob/15-gtfs-validation-pipeline/src/transport_performance/utils/defence.py#L36): 
```python
def _check_parent_dir_exists(pth, param_nm, create=False):
	_is_path_like(pth, param_nm)
	parent = os.path.dirname(pth)
	if not os.path.exists(parent):
		if create:
			os.makedirs(parent)
			print(f"Creating parent directory: {parent}")
	else:
		raise FileNotFoundError(
			f"Parent directory {parent} not found on disk."
		)

	return None
```

Or the `exist_ok` argument could be used to handle the whole 'does the folder already exist' if/else statement internally.

This aspect should also be covered by a unit test (in `test_defense.py`) to prevent reocurrence.

**Environment**

 - OS: macOS
 - Python version: 3.9.13
 - Java version: 11
 - Python module versions (if different from `requirements.txt`):

**Steps to reproduce**

New folder is generated regardless of how many new sub-directories need to be created.

**Comment by SergioRec** [comment]
**Describe the bug**

When running [src/transport_performance/osm/osm_utils.py](https://github.com/datasciencecampus/transport-network-performance/pull/34/files#diff-8388c15a92911f053531b0747bb92b7607c52aaae5c57273777dfda1cc8e933a), if using a path in the `out_pth` argument containing backslashes in the string, this is not recognised as a path and instead creates a file with that character or whatever escape character happens in the filename. Using double slash to prevent escape character just creates a file with the slash in the name.

This behaviour is caused by function [_check_parent_dir_exists()](https://github.com/datasciencecampus/transport-network-performance/blob/96f48a9588b8e119812fad18e21cb8481b325bc5/src/transport_performance/utils/defence.py#L31).

**Environment**
- OS: macOS
- Python version: 3.9.13
- Java version: 11
- Python module versions (if different from requirements.txt):

**Steps to reproduce**
```
>>> filter_osm(out_pth=Path('hello\asdf.pbf'))
"hello sdf.pbf"
>>> filter_osm(out_pth=Path('hello\\asdf.pbf'))
"hello\asdf.pbf"
```
