### ISSUE TITLE
Add capability to select raster layer band in `population` module

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#99]
**Description of the Feature to be Added**

Add capability to select raster layer band in `population` module, as is done in `raster_uc.py`:

https://github.com/datasciencecampus/transport-network-performance/blob/66663568efcd7aa7cd552f25f37c4c1302e6555d/src/transport_performance/urban_centres/raster_uc.py#L25-L36

**Comment by SergioRec** [comment]
Band can be selected using:
```
        self._xds = (
            rioxarray.open_rasterio(self.__filepath, masked=True)
            .sel(band=1)
            .rio.clip([aoi_bounds], from_disk=True, all_touched=True)
        )
```

However, this reduces the shape of the raster from `(1, x, y)` to `(x, y)`, so the `squeeze(axis=0)` in function `_to_geopandas` fails.

If we're never going to be loading more than one band, squeeze needs to be removed. Otherwise, we'll need to add some logic checking the shape of the array.
